---

- hosts: localhost
#  connection: local
  become: true

  tasks:
    - name: update cache
      package:
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/packages.yml