- name: create ansible user
  user:
     name: ixIK4ulE
     system: yes

- name: add sudoers file for ixIK4ulE
  copy:
    src: sudoer_ixIK4ulE
    dest: /etc/sudoers.d/ixIK4ulE
    owner: root
    group: root
    mode: 0440

- name: add sudoers file for test
  copy:
    src: sudoer_test
    dest: /etc/sudoers.d/test
    owner: root
    group: root
    mode: 0440

- name: add users to docker group
  user:
     name: ixIK4ulE
     groups: docker

- name: add users to docker group
  user:
     name: test
     groups: docker

- name: add users to docker group
  user:
     name: simone
     groups: docker